-- =========================================================================
-- Supabase Schema for Sevam (Project: vvltacibwvrwtfhyesur)
-- Safe, idempotent DDL queries for Supabase SQL Editor
-- =========================================================================

-- 1. Actions Table (Logs every user action and event)
CREATE TABLE IF NOT EXISTS public.actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    entity_type TEXT DEFAULT 'general',
    entity_id TEXT,
    user_id BIGINT,
    user_role TEXT,
    details JSONB DEFAULT '{}'::jsonb,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Activity Logs Table (Audit history)
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    entity_type TEXT DEFAULT 'general',
    entity_id TEXT,
    user_id BIGINT,
    user_role TEXT,
    details JSONB DEFAULT '{}'::jsonb,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL,
    role TEXT NOT NULL,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Food Providers Table (Kitchens & Restaurants)
CREATE TABLE IF NOT EXISTS public.food_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    business_name TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    business_type TEXT,
    fssai_status TEXT,
    fssai_number TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Social Working Groups Table (NGOs & Volunteer Circles)
CREATE TABLE IF NOT EXISTS public.social_working_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    group_name TEXT NOT NULL,
    representative_name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    organization_type TEXT,
    darpan_id TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Food Listings Table (Surplus food published by providers)
CREATE TABLE IF NOT EXISTS public.food_listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT,
    category_id BIGINT,
    food_name TEXT NOT NULL,
    food_type TEXT DEFAULT 'Veg',
    quantity NUMERIC(10,2) DEFAULT 0,
    available_quantity NUMERIC(10,2) DEFAULT 0,
    quantity_unit TEXT DEFAULT 'kg',
    price NUMERIC(10,2) DEFAULT 0,
    available_date DATE,
    available_start_time TIME,
    available_end_time TIME,
    expiry_date DATE,
    expiry_time TIME,
    pickup_info TEXT,
    status TEXT DEFAULT 'Available',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Food Requests Table (Claims by social working groups)
CREATE TABLE IF NOT EXISTS public.food_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id BIGINT,
    group_id BIGINT,
    requested_quantity NUMERIC(10,2) NOT NULL,
    requested_date DATE,
    requested_time TIME,
    status TEXT DEFAULT 'Pending',
    message TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Contact Messages Table (Public inquiries)
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    subject TEXT,
    message TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Grant access to anon and authenticated roles
GRANT ALL ON TABLE public.actions TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.activity_logs TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.users TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.food_providers TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.social_working_groups TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.food_listings TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.food_requests TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.contact_messages TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- Enable Row Level Security and configure non-destructive permissive policies
ALTER TABLE public.actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.food_providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_working_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.food_listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.food_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "actions_access_policy" ON public.actions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "activity_logs_access_policy" ON public.activity_logs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "users_access_policy" ON public.users FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "providers_access_policy" ON public.food_providers FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "groups_access_policy" ON public.social_working_groups FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "listings_access_policy" ON public.food_listings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "requests_access_policy" ON public.food_requests FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "messages_access_policy" ON public.contact_messages FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
